# Generated by Django 4.1 on 2022-09-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='proudct',
            new_name='product',
        ),
    ]
